### ISSUE TITLE
Query Regarding Oracle Section in Your Project

### ISSUE THREAD

**Issue by LMP42** [frenkowski/SCIMAI-Gym#5]
I hope this message finds you well. I am currently a student exploring your project on GitHub, and I've been encountering some difficulties understanding the Oracle section. Despite my efforts, I haven't been able to locate any Oracle-related components within the project.

I am keen on delving deeper into the Oracle section of your project, as I believe it would greatly benefit my learning and understanding of the project as a whole. Could you kindly direct me to where I can find the Oracle section within the project, or perhaps offer some guidance on how to further explore this aspect?

I truly appreciate your time and assistance. Your project has captured my interest, and I am eager to gain more insights into it.

Thank you very much.

**Comment by frenkowski** [comment]
Thank you very much for your message and for showing such keen interest in our project.

In the `ECML-PKDD_SCIMAI-Gym.ipynb` file, the Oracle is present in the section titled "Oracle." This part of the project assumes that the Oracle is an agent capable of satisfying demand at every timestep 100% without incurring storage or penalty costs, paying only for production and transportation. However, it is important to note that this assumption holds only for experiments related to the `ECML-PKDD_SCIMAI-Gym.ipynb` file.

On the other hand, the section you are looking for in the` IJPE_SCIMAI-Gym.ipynb` file is named "OR-Tools Methods," specifically referencing an agent called LP-DET. The experiments in this file introduce additional constraints, such as transportation times, fixed transportation costs related to trucks, reduced factory capacity compared to warehouses, etc. Due to these constraints, we implemented a linear programming agent that knows the future demand in advance and can, consequently, select the best action for each timestep (this, of course, is a scenario that is unlikely to occur in the real world).

For a detailed explanation of the environment, the various assumptions of the problem, and the Oracle, you can read the two associated papers published and available on my [Google Scholar profile](https://scholar.google.com/citations?user=XUpEKbIAAAAJ).

I hope this response thoroughly addresses your queries. Wishing you a pleasant day and all the best with your further exploration of the project!
